# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

references:
  js_deps_cache_key: &js_deps_cache_key
    v1-dependency-js-deps-{{ checksum "package.json" }}
  js_deps_backup_cache_key: &js_deps_backup_cache_key
    v1-dependency-js-deps
  node_latest: &node_latest
    circleci/node:11
  node_lts: &node_lts
    circleci/node:10

defaults: &defaults
  steps:
    - checkout
    - run: exit 0 # exit early?
    - run: npm install
    - run: ./node_modules/.bin/jsvu --os=linux64 --engines=$hostName
    - run: cp -r  ~/.jsvu/engines/$hostName r
    - run: ls -lsa r/
    - run: ./node_modules/.bin/test262-harness --hostPath=$hostPath --hostType=$hostType -- 'test/**/*'

restore_cache: &restore_cache
  restore_cache:
    keys:
      - *js_deps_cache_key
      - *js_deps_backup_cache_key

save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
    key: *js_deps_cache_key

jobs:
  "testing git":
    docker:
      - image: *node_latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    working_directory: ~/bots
    environment:
      hostType: d8
      hostPath: r/v8
      hostName: v8
      jsvu: ./node_modules/.bin/jsvu
    <<: [*defaults]
workflows:
  version: 2
  tests:
    jobs:
      - "testing git"
