# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

references:
  js_deps_cache_key: &js_deps_cache_key
    v1-dependency-js-deps-{{ checksum "package.json" }}
  js_deps_backup_cache_key: &js_deps_backup_cache_key
    v1-dependency-js-deps
  node_latest: &node_latest
    circleci/node:11
  node_lts: &node_lts
    circleci/node:10

restore_cache: &restore_cache
  restore_cache:
    keys:
      - *js_deps_cache_key
      - *js_deps_backup_cache_key

save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
    key: *js_deps_cache_key

jobs:
  "tests for v8":
    docker:
      - image: *node_latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    working_directory: ~/bots
    environment:
      hostType: d8
      hostPath: ~/.jsvu/v8
      jsvu: ./node_modules/.bin/jsvu
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: $jsvu --os=linux64 --engines=v8
      - run: npm test
  "tests for v8_harmony":
    docker:
      - image: *node_latest
    working_directory: ~/bots
    environment:
      hostType: d8
      hostPath: ~/.jsvu/v8
      hostArgs: --harmony
      jsvu: ./node_modules/.bin/jsvu
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: $jsvu --os=linux64 --engines=v8
      - run: npm test
  "tests for spidermonkey":
    docker:
      - image: *node_latest
    working_directory: ~/bots
    environment:
      hostType: jsshell
      hostPath: ~/.jsvu/spidermonkey
      jsvu: ./node_modules/.bin/jsvu
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: $jsvu --os=linux64 --engines=spidermonkey
      - run: npm test
  "tests for chakra":
    docker:
      - image: *node_latest
    working_directory: ~/bots
    environment:
      hostType: ch
      hostPath: ~/.jsvu/chakra
      jsvu: ./node_modules/.bin/jsvu
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: $jsvu --os=linux64 --engines=chakra
      - run: npm test
  "tests for jsc":
    docker:
      - image: *node_latest
    working_directory: ~/bots
    environment:
      hostType: jsc
      hostPath: ~/.jsvu/jsc
      jsvu: ./node_modules/.bin/jsvu
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: $jsvu --os=linux64 --engines=jsc
      - run: npm test
  "tests for node_lts":
    docker:
      - image: *node_lts
    working_directory: ~/bots
    environment:
      hostType: node
      hostPath: node
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm test
  "tests for node_latest":
    docker:
      - image: *node_latest
    working_directory: ~/bots
    environment:
      hostType: node
      hostPath: node
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm test
workflows:
  version: 2
  test_chakra:
    jobs:
      - "tests for chakra"
  test_jsc:
    jobs:
      - "tests for jsc"
  test_spidermonkey:
    jobs:
      - "tests for spidermonkey"
  test_v8:
    jobs:
      - "tests for v8"
  test_v8_harmony:
    jobs:
      - "tests for v8_harmony"
  test_node_lts:
    jobs:
      - "tests for node_lts"
  test_node_latest:
    jobs:
      - "tests for node_latest"
