# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

references:
  js_deps_cache_key: &js_deps_cache_key
    v1-dependency-js-deps-{{ checksum "package.json" }}
  js_deps_backup_cache_key: &js_deps_backup_cache_key
    v1-dependency-js-deps
  node_latest: &node_latest
    circleci/node:11
  node_lts: &node_lts
    circleci/node:10

restore_cache: &restore_cache
  restore_cache:
    keys:
      - *js_deps_cache_key
      - *js_deps_backup_cache_key

save_cache: &save_cache
  save_cache:
    paths:
      - node_modules
    key: *js_deps_cache_key

presteps: &presteps
  - checkout
  - *restore_cache
  - run: npm install
  - *save_cache

settings: &settings
  working_directory: ~/bots
  branches:
    ignore: master

jobs:
  test_v8:
    docker:
      - image: *node_latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    <<: [*settings]
    environment:
      hostType: d8
      hostPath: ~/.jsvu/v8
    steps:
      <<: [*presteps]
      - run: jsvu --os=linux64 --engines=v8
      - run: npm test
  test_v8_harmony:
    docker:
      - image: *node_latest
    <<: [*settings]
    environment:
      hostType: d8
      hostPath: ~/.jsvu/v8
      hostArgs: --harmony
    steps:
      <<: [*presteps]
      - run: jsvu --os=linux64 --engines=v8
      - run: npm test
  test_spidermonkey:
    docker:
      - image: *node_latest
    <<: [*settings]
    environment:
      hostType: jsshell
      hostPath: ~/.jsvu/spidermonkey
    steps:
      <<: [*presteps]
      - run: jsvu --os=linux64 --engines=spidermonkey
      - run: npm test
  test_chakra:
    docker:
      - image: *node_latest
    <<: [*settings]
    environment:
      hostType: ch
      hostPath: ~/.jsvu/chakra
    steps:
      <<: [*presteps]
      - run: jsvu --os=linux64 --engines=chakra
      - run: npm test
  test_jsc:
    docker:
      - image: *node_latest
    <<: [*settings]
    environment:
      hostType: jsc
      hostPath: ~/.jsvu/jsc
    steps:
      <<: [*presteps]
      - run: jsvu --os=linux64 --engines=jsc
      - run: npm test
  test_node_lts:
    docker:
      - image: *node_lts
    <<: [*settings]
    environment:
      hostType: node
      hostPath: node
    steps:
      <<: [*presteps]
      - run: npm test
  test_node_latest:
    docker:
      - image: *node_latest
    <<: [*settings]
    environment:
      hostType: node
      hostPath: node
    steps:
      <<: [*presteps]
      - run: npm test
workflows:
  version: 2
  test_chakra:
    jobs:
      - test_chakra
  test_jsc:
    jobs:
      - test_jsc
  test_spidermonkey:
    jobs:
      - test_spidermonkey
  test_v8:
    jobs:
      - test_v8
  test_v8_harmony:
    jobs:
      - test_v8_harmony
  test_node_lts:
    jobs:
      - test_node_lts
  test_node_latest:
    jobs:
      - test_node_latest
